-- Structured decision workflow, option provenance, and private per-user
-- clarification-policy learning.

alter table public.decision_options
  add column if not exists source text not null default 'user_provided'
    check (source in ('user_provided', 'ai_extracted', 'ai_generated')),
  add column if not exists status text not null default 'candidate'
    check (status in ('candidate', 'confirmed', 'rejected')),
  add column if not exists metadata jsonb not null default '{}'::jsonb;

create table if not exists public.clarification_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  profile jsonb not null default '{"schema_version":1,"total_interactions":0,"action_stats":{},"preferences":{}}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.clarification_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  decision_id uuid not null references public.decisions(id) on delete cascade,
  message_id uuid references public.decision_messages(id) on delete set null,
  action_category text not null,
  selected_question text,
  context jsonb not null default '{}'::jsonb,
  outcome text check (outcome in ('answered', 'skipped')),
  reward numeric,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists clarification_events_user_created_idx
  on public.clarification_events (user_id, created_at desc);
create index if not exists clarification_events_decision_created_idx
  on public.clarification_events (decision_id, created_at desc);

drop trigger if exists clarification_profiles_set_updated_at on public.clarification_profiles;
create trigger clarification_profiles_set_updated_at
before update on public.clarification_profiles
for each row execute function public.set_updated_at();

drop trigger if exists clarification_events_set_updated_at on public.clarification_events;
create trigger clarification_events_set_updated_at
before update on public.clarification_events
for each row execute function public.set_updated_at();

alter table public.clarification_profiles enable row level security;
alter table public.clarification_events enable row level security;

create policy "Users can read their own clarification profile"
on public.clarification_profiles for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can read their own clarification events"
on public.clarification_events for select to authenticated
using ((select auth.uid()) = user_id);

-- Learning records are generated by the trusted backend. Users can read their
-- own records for transparency and data export, but cannot train the policy by
-- editing rewards directly.
revoke all on table public.clarification_profiles from anon, authenticated;
revoke all on table public.clarification_events from anon, authenticated;
grant select on table public.clarification_profiles to authenticated;
grant select on table public.clarification_events to authenticated;

create or replace function public.prevent_completed_option_changes()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  parent_status text;
begin
  if tg_op = 'DELETE' then
    select status into parent_status from public.decisions where id = old.decision_id;
  else
    select status into parent_status from public.decisions where id = new.decision_id;
  end if;
  if parent_status = 'completed' then
    raise exception 'Options cannot be changed after a decision is completed';
  end if;
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists decision_options_lock_completed on public.decision_options;
create trigger decision_options_lock_completed
before insert or update or delete on public.decision_options
for each row execute function public.prevent_completed_option_changes();
